### PR TITLE
Support qBittorrent v4.2.1, fixes #46

### LINKED ISSUE #46: New api support?
Hi, is possible to support new api from version 4.2?
More here
https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#get-torrent-list

### PR DESCRIPTION
**Pull request by colingpt**
# Motivation for changes:
- ART stopped working with qBittorrent v4.2.1

# Detailed changes:
- Update to qBittorrent [Web API V2.3.0](https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation)

# Addressed issues:
- Fixes #46 

# PS
- Newbie here, just tried to edit local /client/qbittorrent.py, and it seems working fine for me.

### CODE REVIEW

**Comment by xiuluo** [comment]
Fri, 03 Jan 2020 15:33:27 main.py[line:44] INFO Auto Remove Torrents 1.4.6
Fri, 03 Jan 2020 15:33:27 main.py[line:46] INFO Loading configurations...
Fri, 03 Jan 2020 15:33:27 main.py[line:49] INFO Found 1 task(s) in the file.
Fri, 03 Jan 2020 15:33:27 task.py[line:115] INFO Running task 'my_task'...
Fri, 03 Jan 2020 15:33:27 task.py[line:75] INFO Logging in...
Fri, 03 Jan 2020 15:33:27 task.py[line:80] INFO Login successfully. The client is qBittorrent v4.2.1.
Fri, 03 Jan 2020 15:33:27 task.py[line:84] INFO Getting all the torrents...
Fri, 03 Jan 2020 15:33:27 main.py[line:57] ERROR TypeError: __init__() missing 1 required positional argument: 'seeding_time'
Fri, 03 Jan 2020 15:33:27 main.py[line:58] ERROR Task my_task fails. 
Fri, 03 Jan 2020 15:33:27 main.py[line:59] DEBUG Exception Logged
Traceback (most recent call last):
  File "c:\users\shura\scoop\apps\python\current\lib\site-packages\autoremovetorrents\main.py", line 55, in pre_processor
    Task(task_name, result[task_name], not view_mode).execute()
  File "c:\users\shura\scoop\apps\python\current\lib\site-packages\autoremovetorrents\task.py", line 117, in execute
    self._get_torrents()
  File "c:\users\shura\scoop\apps\python\current\lib\site-packages\autoremovetorrents\task.py", line 88, in _get_torrents
    self._torrents.add(self._client.torrent_properties(hash_value))
  File "c:\users\shura\scoop\apps\python\current\lib\site-packages\autoremovetorrents\client\qbittorrent.py", line 100, in torrent_properties
    properties['seeding_time'])
TypeError: __init__() missing 1 required positional argument: 'seeding_time'

**Comment by jerrymakesjelly** [comment]
Thanks for your PR, but this code removes the compatibility with the older version of the API, and the users who are using the old version of qBittorrent will no longer be able to use this program.

Would you like to add a API version checker to make it compatible with all of the versions of the API? Or, let me implement this 😄

**Comment by jerrymakesjelly** [comment]
> TypeError: **init**() missing 1 required positional argument: 'seeding_time'

This PR is based on version 1.2.4. It cannot be simply merged by replacing the file `qbittorrent.py` .

**Comment by colingpt** [comment]
@jerrymakesjelly 

This PR is just a temporary fix for me and those who were waiting for your offical fix 😄 .

As I am new to programing, I learned your code carefully (I haven't updated to v1.4.7 yet). Here are my a few confusions:

https://github.com/jerrymakesjelly/autoremove-torrents/blob/abd6fd2c5d669e0e3a27a0d6bcf101b1d384e6a0/autoremovetorrents/client/qbittorrent.py#L59

and 

https://github.com/jerrymakesjelly/autoremove-torrents/blob/abd6fd2c5d669e0e3a27a0d6bcf101b1d384e6a0/autoremovetorrents/client/qbittorrent.py#L108

1. It seems that the function delete_torrent_and_data doesn't need a 'return'?

2. And for V2 api, you used GET for delete_torrent, but POST for delete_torrent_and_data.

3. Does the command/delete still work for webapi v2.4.0. https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#delete-torrents

May I know why?

Any hint about above questions is very appreciated.

Again, thank you for your amazing work and continuous contriution.

**Comment by jerrymakesjelly** [comment]
> May I know why?

Sorry it is a mistake, and in my test it doesn't work due to the wrong request method. All of the methods should have a return value. I will fix this problem as soon as possible.

By the way, in the current version I didn't use the return values of the deletion method, because they don't have any response content, except HTTP status code. So missing a `return` has no effect, although it is a mistake.

In the future version, to ensure the deletion operation is completed correctly, I will check the HTTP status code.

Thank you for your review!

**Comment by colingpt** [comment]
Thank you. I will close this then.
